title: "Balaji Arun" # the name of your site, e.g. ACME Corp.
tagline: "PhD student at Virginia Tech"
# email: your.email@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Balaji's Personal Webpage
author: Balaji Arun
url: "https://ibalajiarun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
# google_analytics: UA-111111111-1
twitter:
  username: ibalajiarun
  card: summary #keep this to generate a twitter share card

sass:
  sass_dir: _sass

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap